name: Terraform Destroy
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'us-east-1'

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug AWS Env Vars
      run: env | grep AWS

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Run input_generator.py
      run: python scripts/input_generator.py input/user_input.txt

    - name: Run gen_tfvars.py
      run: python scripts/gen_tfvars.py

    - name: Run policy_generator.py
      run: python scripts/policy_generator.py

    - name: Setup backend
      run: sh scripts/update_backend.sh

    - name: Terraform Init
      run: terraform init -backend-config=backend.tfbackend
      working-directory: terraform/environments/

    - name: Terraform Destroy
      run: terraform destroy -var-file=auto_inputs.tfvars.json -auto-approve
      working-directory: terraform/environments/
